### PR TITLE
Update 01-introduction.md

### PR DESCRIPTION
**Pull request by bkmgit**
Remove reference to Google+ which is no longer available as indicated in issue #55

### CODE REVIEW

**Comment by brownsarahm** [comment]
Removing Google+ is a great idea, but I'm not certain about adding Twitter as a source. I'm tagging the other maintainers to chime in on that.

**Comment by gtlaflair** [comment]
Yes! Thank you for the suggestion! I agree with @brownsarahm and @isawil about Twitter.

**Comment by bkmgit** [comment]
Thanks for the suggestions. Twitter removed.

**Comment by bkmgit** [comment]
This also seems addressed in #50

**Comment by brownsarahm** [comment]
Thanks @bkmgit for also noticing this is duplicate to #50. I closed that too.

**Pull request merged**
