### PR TITLE
Update 02-working-with-openrefine.md

### PR DESCRIPTION
**Pull request by mlandryacenet**
Add "If you have not started OpenRefine yet, follow the [Setup instructions](https://datacarpentry.org/openrefine-socialsci/setup.html) before continuing."

### CODE REVIEW

**Comment by bencomp** [comment]
Hi @mlandryacenet, thanks for your pull request. It looks like a small but useful addition. Out of curiousity, did you find this was missing while you were teaching?

I do also feel that we should not copy the instructions for (installing and) running OpenRefine in too many places. I recently found that there are issues with starting OpenRefine that were new to me (#132). So that whole paragraph is probably too simplistic.
What would you think of removing the paragraph and replacing it with a link to the setup section for reference?

**Comment by mlandryacenet** [comment]
Hi @bencomp, that is actually a really good point. My first thought was that since we are repeating the information from the Setup page for just Windows and Mac on this page, it would be helpful to also link the URLs as an additional way to access OpenRefine. However, now I think it would make most sense to omit the paragraph altogether and redirect the user with a link to the Setup page. The paragraph is a bit simplistic and the Setup page would be the best place to elaborate on the different ways in which one can access OpenRefine.

**Comment by bencomp** [comment]
Would you be able to update this PR with the new text? I feel it could be something like "If you have not started OpenRefine yet, follow the *setup instructions* before continuing." I am open to other suggestions.

**Comment by mlandryacenet** [comment]
I am very new to GitHub, so I apologize if I didn't update the PR correctly or possibly messed things up. Hopefully this works!

**Pull request merged**
