### PR TITLE
Add lesson learning objectives, move Getting Help

### LINKED ISSUE #38: Explain goals of the lesson more clearly in the Introduction
Hi, 

I'd like to suggest a new/modified objective for the Data Cleaning module - Introduction, more focused on learning outcomes.

Participants will be able to process data in order to ensure that it is correct, consistent, and useable by detecting any errors in the data, correcting or removing corruptions in the data, or manually modifying or deleting the coarse data as needed.

Hope this is useful.

Cheers,
Deena Yanofsky

### PR DESCRIPTION
**Pull request by bencomp**
This fixes #38. It also relates to #122.

Overview:

- add lesson learning objectives, not to the introduction (#38) but Summary and Setup (as in [Lesson Development Training](https://carpentries.github.io/lesson-development-training/index.html))
- move "Getting Help" from Introduction to Other Resources (almost #122)

I don't think I wrote new learning objectives, but perhaps the @datacarpentry/curriculum-advisors-social-science would like to check?

### CODE REVIEW

**Comment by ndporter** [comment]
I think moving the "getting help" section makes sense, although the relevant learning objective should also be moved from Episode 1 to the later episode.

Adding overall objectives to the main lesson page also fits best practice and seems good to me.

**Review by ndporter — CHANGES_REQUESTED** [review]
Please move the objective related to additional resources from episode 01 to episode 07 (to match the move of the text).

**Comment by bencomp** [comment]
Thanks for checking, @ndporter! Indeed the objective should have moved along with the contents.

Although if I add it to Other Resources, these are its LOs:

- Understand that there are many online resources available for more information on OpenRefine.
- Locate helpful resources to learn more about OpenRefine.
- Identify other resources about OpenRefine.

I don't think we need the more or less the same objective three times. (I don't think we should have this as an episode at all, but that is still waiting for CAC advice in #122 :))
I will leave out the "Identify" LO.

**Comment by ndporter** [comment]
The changes to LOs look good. We'll bring #122 up with the CAC next meeting.

**Review by ndporter — APPROVED** [review]

**Pull request merged**
