### PR TITLE
Update styles files and broken links

### PR DESCRIPTION
**Pull request by bencomp**
When talking to @tobyhodges, we found that #113 was not a good replacement for #81. I discussed with @tobyhodges that I would update the style for the repository and replace the old style links with the [current suggested way](https://carpentries.github.io/lesson-example/04-formatting/index.html#locations-and-names). 

I hadn't realised that we were 200+ commits behind on the carpentries/styles repository. I limited updates to style-related ones in this PR.

The original issue was about links (not) working. I tested the results manually using both `make serve` (i.e. Jekyll with HTTP) and `make site` (i.e. Jekyll static files) with success.

### CODE REVIEW

**Review by tobyhodges — APPROVED** [review]
This looks good on my local build too.

**Comment by tobyhodges** [comment]
Out of curiosity, why does each episode start with a heading saying "Lesson"?

**Comment by bencomp** [comment]
Thanks, @tobyhodges. The "lesson" is a remnant of long ago and it's one of the many smaller things to be fixed. I guess the original authors felt every markdown file needed to have a level 1 heading?

**Comment by tobyhodges** [comment]
In terms of accessibility, it is important that each page has only one first level-heading, so these extra headings should definitely be removed. I'll open an issue.

**Pull request merged**
