### PR TITLE
Solve java issue with OpenRefine 3.4 beta 2

### PR DESCRIPTION
**Pull request by Lucia-Michielin**
Add the information about the Windows kit with embedded Java of the OpenRefine 3.4 beta 2 release

Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by Lucia-Michielin** [comment]
Hello! I added the info about of the Windows kit with embedded java of the OpenRefine 3.4 beta 2 release.
This is a quick solve for Java issues mostly if you are running the workshop online

**Comment by brownsarahm** [comment]
Thanks @Lucia-Michielin I removed a tiny extraneous space, but otherwise I think this is a great idea. 

However, I think it would be better if we link to the page where people can choose the file to download. Those links are more persistent; the file direct link is like to change or break.  Could you change the link to the page that has the file download link on it?

**Comment by Lucia-Michielin** [comment]
Hi Sarah,
Thanks! done it!

**Comment by brownsarahm** [comment]
Thanks @Lucia-Michielin

**Pull request merged**
